spring.application.name=Week3HibernateJPA
spring.datasource.url=jdbc:mysql://localhost:3306/coding_shuttle?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=suresh
spring.datasource.password=suresh
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
